# Generated by Django 2.2.1 on 2019-05-20 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=144, verbose_name='Alan Adı')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domainler',
            },
        ),
        migrations.CreateModel(
            name='Backlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, verbose_name='Link')),
                ('keyword', models.CharField(max_length=100, verbose_name='Anahtar Kelime')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eklenme Tarihi')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eklenme Tarihi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ek Bilgi')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backlinks.Domain', verbose_name='Alan Adı')),
            ],
            options={
                'verbose_name': 'Backlink',
                'verbose_name_plural': 'Backlinkler',
            },
        ),
    ]
