# Generated by Django 2.2.1 on 2019-06-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlinks',
            name='author',
        ),
    ]
