# Generated by Django 2.2.1 on 2019-05-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlinks', '0002_auto_20190521_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlinks',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
