# Generated by Django 2.2.1 on 2019-06-01 20:07

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backlinks', '0003_backlinks_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlinks',
            name='added_by',
        ),
        migrations.AddField(
            model_name='backlinks',
            name='author',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mymodels', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned'),
        ),
    ]
